### PR TITLE
how to run this demo

### PR DESCRIPTION
**Pull request by akoskm**
This might be obvious for some but I think it should stay somewhere in the README.

### CODE REVIEW

**Comment by nkbt** [comment]
There is a section Start in Readme:



There is nothing about `npm install` though.. Maybe that one is worth adding? Sort of like [here](https://github.com/nkbt/react-component-template#development-and-testing)?

**Comment by akoskm** [comment]
> Sort of like here?

Yes, it should be listed under a more obvious section like "Install" or "Install Instructions" and the same section should contain every command you need to execute in order to run the demo.

Like under your link or here: https://github.com/carlosazaustre/universal-js-boilerplate#requirements-and-install

**Comment by ericelliott** [comment]
Can you call it "Getting Started" and list it closer to the top of the README (just under the status section, maybe?)

**Comment by akoskm** [comment]
Good idea! Corrected.

**Pull request merged**
