### PR TITLE
Add .babelrc

### PR DESCRIPTION
**Pull request by zebulonj**
Override babel ignore defaults to transpile internal node_modules directories (closes cloverfield-tools/universal-react-boilerplate#41).

### CODE REVIEW

**Comment by zebulonj** [comment]
Hold merging this. I'm not sure that it works via the .babelrc the way we want.

**Comment by ericelliott** [comment]
OK... let me know when you're ready for a review.

**Comment by ericelliott** [comment]
What's the status of this?

**Comment by vasco3** [comment]
babel ignores node_modules by default https://babeljs.io/docs/usage/cli/

**Pull request closed without merging**
