### PR TITLE
Replaced redux-simple-router with react-router-redux

### PR DESCRIPTION
**Pull request by svenanders**
Did an npm install and noticed it was renamed, so this is a simple fix for that.

### CODE REVIEW

**Comment by ericelliott** [comment]
Thanks. I've already fixed this in my own branch, but I won't be done with my changes for a while.

**Comment by vasco3** [comment]
uhm, why do you need the same component in devDependencies and dependencies?

**Comment by ericelliott** [comment]
We don't. Want to PR?

**Comment by vasco3** [comment]
got it, PR #79

**Comment by svenanders** [comment]
:)

**Pull request merged**
